=== brunovieira97/unisinos-bd2-tga/other/CadastroPedido.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"> 
	<xs:element name="CadastroPedido">
        <xs:complexType>
			<xs:sequence>
				<xs:element name="Pedido" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="CodigoPedido" 	type="xs:integer"/>
							<xs:element name="ValorTotal" 		type="xs:decimal"/> 
							<xs:element name="Situacao" 		type="xs:string"/>
							<xs:element name="DataPedido" 		type="xs:date"/>
							<xs:element name="CodigoEndereco" 	type="xs:integer"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== brunovieira97/unisinos-bd2-tga/other/CadastroPedido.xml
<?xml version="1.0" encoding="UTF-8"?>
<CadastroPedido xsi:noNamespaceSchemaLocation="CadastroPedido.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Pedido>
		<CodigoPedido>1</CodigoPedido>
		<ValorTotal>200</ValorTotal>
		<Situacao>Aprovado</Situacao>
		<DataPedido>2019-04-01</DataPedido>
		<CodigoEndereco>3</CodigoEndereco>
	</Pedido>	
	<Pedido>
		<CodigoPedido>2</CodigoPedido>
		<ValorTotal>150</ValorTotal>
		<Situacao>Pendente</Situacao>
		<DataPedido>2019-04-10</DataPedido>
		<CodigoEndereco>3</CodigoEndereco>
	</Pedido>
</CadastroPedido>
