=== brunovieira97/unisinos-bd2-tga/other/CadastroEndereco.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"> 
	<xs:element name="CadastroEndereco">
        <xs:complexType>
			<xs:sequence>
				<xs:element name="Endereco" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="CodigoEndereco" 	type="xs:integer"/>
							<xs:element name="Logradouro" 		type="xs:string"/>
							<xs:element name="Numero" 			type="xs:string"/>
							<xs:element name="Complemento" 		type="xs:string"/>
							<xs:element name="Bairro" 			type="xs:string"/>
							<xs:element name="Cidade" 			type="xs:string"/>
							<xs:element name="Estado" 			type="xs:string"/>
							<xs:element name="Pais" 			type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== brunovieira97/unisinos-bd2-tga/other/CadastroEndereco.xml
<?xml version="1.0" encoding="UTF-8"?>
<CadastroEndereco xsi:noNamespaceSchemaLocation="CadastroEndereco.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Endereco>
		<CodigoEndereco>1</CodigoEndereco>
		<Logradouro> Av. Unisinos</Logradouro>
		<Numero>950</Numero>
		<Complemento></Complemento>
		<Bairro>Cristo Rei</Bairro>
		<Cidade>SÃ£o Leopoldo</Cidade>
		<Estado>RS</Estado>
		<Pais>BR</Pais>
	</Endereco>	
	<Endereco>
		<CodigoEndereco>2</CodigoEndereco>
		<Logradouro> Av. Floresta</Logradouro>
		<Numero>524</Numero>
		<Complemento>205</Complemento>
		<Bairro>Ideal</Bairro>
		<Cidade>Novo Hamburgo</Cidade>
		<Estado>RS</Estado>
		<Pais>BR</Pais>
	</Endereco>	
	<Endereco>
		<CodigoEndereco>3</CodigoEndereco>
		<Logradouro> Av. Fererico Ruan</Logradouro>
		<Numero>1024</Numero>
		<Complemento></Complemento>
		<Bairro>Centro</Bairro>
		<Cidade>Porto Alegre</Cidade>
		<Estado>RS</Estado>
		<Pais>BR</Pais>
	</Endereco>	
</CadastroEndereco>
