=== brunovieira97/unisinos-bd2-tga/other/CadastroItens.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="CadastroItens">
        <xs:complexType>
			<xs:sequence>
				<xs:element name="PedidoItem" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="CodigoPedidoItem" 	type="xs:integer"/>
							<xs:element name="CodigoPedido" 		type="xs:integer"/>
							<xs:element name="CodigoProduto" 		type="xs:integer"/>
							<xs:element name="Quantidade" 			type="xs:integer"/>
							<xs:element name="Valor" 				type="xs:decimal"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== brunovieira97/unisinos-bd2-tga/other/CadastroItens.xml
<?xml version="1.0" encoding="UTF-8"?>
<CadastroItens xsi:noNamespaceSchemaLocation="CadastroItens.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<PedidoItem>
		<CodigoPedidoItem>1</CodigoPedidoItem>
		<CodigoPedido>1</CodigoPedido>
		<CodigoProduto>1</CodigoProduto>
		<Quantidade>1</Quantidade>
		<Valor>100</Valor>
	</PedidoItem>	
	<PedidoItem>
		<CodigoPedidoItem>2</CodigoPedidoItem>
		<CodigoPedido>2</CodigoPedido>
		<CodigoProduto>2</CodigoProduto>
		<Quantidade>1</Quantidade>
		<Valor>50</Valor>
	</PedidoItem>	
	<PedidoItem>
		<CodigoPedidoItem>3</CodigoPedidoItem>
		<CodigoPedido>2</CodigoPedido>
		<CodigoProduto>1</CodigoProduto>
		<Quantidade>1</Quantidade>
		<Valor>50</Valor>
	</PedidoItem>	
</CadastroItens>
