=== brunovieira97/unisinos-bd2-tga/other/CadastroCliente.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"> 
	<xs:element name="CadastroCliente">
        <xs:complexType>
			<xs:sequence>
				<xs:element name="Cliente" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="CodigoCliente" 	type="xs:integer"/>
							<xs:element name="Nome" 		 	type="xs:string"/>
							<xs:element name="CPF" 			 	type="xs:string"/>
							<xs:element name="CodigoEndereco" 	type="xs:integer"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>		
</xs:schema>

=== brunovieira97/unisinos-bd2-tga/other/CadastroCliente.xml
<?xml version="1.0" encoding="UTF-8"?>
<CadastroCliente xsi:noNamespaceSchemaLocation="CadastroCliente.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Cliente>
		<CodigoCliente>1</CodigoCliente>
		<Nome>Taiyuki So</Nome>
		<CPF>427.502.150-99</CPF>
		<CodigoEndereco>1</CodigoEndereco>
	</Cliente>
	<Cliente>
		<CodigoCliente>2</CodigoCliente>
		<Nome>Bruno Vieira</Nome>
		<CPF>604.925.200-97</CPF>
		<CodigoEndereco>2</CodigoEndereco>
	</Cliente>
</CadastroCliente>
