=== brunovieira97/unisinos-bd2-tga/other/CadastroProduto.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"> 
	<xs:element name="CadastroProduto">
        <xs:complexType>
			<xs:sequence>
				<xs:element name="Produto" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="CodigoProduto" 		type="xs:integer"/>
							<xs:element name="Descricao" 		 	type="xs:string"/>
							<xs:element name="ValorUnitario" 		type="xs:decimal"/>
							<xs:element name="CodigoFornecedor" 	type="xs:integer"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== brunovieira97/unisinos-bd2-tga/other/CadastroProduto.xml
<?xml version="1.0" encoding="UTF-8"?>
<CadastroProduto xsi:noNamespaceSchemaLocation="CadastroProduto.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Produto>
		<CodigoProduto>1</CodigoProduto>
		<Descricao>Monitor</Descricao>
		<ValorUnitario>100</ValorUnitario>
		<CodigoFornecedor>1</CodigoFornecedor>
	</Produto>	
	<Produto>
		<CodigoProduto>2</CodigoProduto>
		<Descricao>Teclado</Descricao>
		<ValorUnitario>50</ValorUnitario>
		<CodigoFornecedor>1</CodigoFornecedor>
	</Produto>	
</CadastroProduto>
