=== brunovieira97/unisinos-bd2-tga/other/VinculoPedido.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="VinculoPedido">
        <xs:complexType>
			<xs:sequence>
				<xs:element name="ClientePedido" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="CodigoPedido" 	type="xs:integer"/>
							<xs:element name="CodigoCliente" 	type="xs:integer"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== brunovieira97/unisinos-bd2-tga/other/VinculoPedido.xml
<?xml version="1.0" encoding="UTF-8"?>
<VinculoPedido xsi:noNamespaceSchemaLocation="VinculoPedido.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<ClientePedido>
		<CodigoPedido>1</CodigoPedido>
		<CodigoCliente>1</CodigoCliente>
	</ClientePedido>	
	<ClientePedido>
		<CodigoPedido>1</CodigoPedido>
		<CodigoCliente>2</CodigoCliente>
	</ClientePedido>	
	<ClientePedido>
		<CodigoPedido>1</CodigoPedido>
		<CodigoCliente>1</CodigoCliente>
	</ClientePedido>	
</VinculoPedido>
